import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { query } from '@/lib/db';
import { logAction } from '@/lib/audit';

const VALID_TYPES = ['faculty', 'staff', 'student'] as const;
type PersonType = typeof VALID_TYPES[number];

const TABLE_MAP: Record<PersonType, { table: string; numField: string }> = {
  faculty: { table: 'faculty',  numField: 'faculty_number' },
  staff:   { table: 'staff',    numField: 'staff_number'   },
  student: { table: 'students', numField: 'student_number' },
};

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  try {
    const { searchParams } = new URL(req.url);
    const ids  = searchParams.get('ids') || '';
    const type = (searchParams.get('type') || 'faculty') as PersonType;
    if (!VALID_TYPES.includes(type)) return NextResponse.json([]);
    const idList = ids.split(',').map(Number).filter(n => Number.isInteger(n) && n > 0);
    if (!idList.length) return NextResponse.json([]); // guard: empty IN() would be SQL error
    const placeholders = idList.map(() => '?').join(',');
    const rows = await query<any[]>(
      `SELECT person_id FROM generated_ids WHERE person_id IN (${placeholders}) AND person_type=?`,
      [...idList, type]
    );
    return NextResponse.json(rows.map(r => r.person_id));
  } catch { return NextResponse.json([]); }
}

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  if ((session.user as any)?.userType !== 'admin')
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  try {
    const { person_id, person_type } = await req.json();
    // Validate inputs
    if (!person_id || !person_type)
      return NextResponse.json({ error: 'person_id and person_type required' }, { status: 400 });
    if (!VALID_TYPES.includes(person_type))
      return NextResponse.json({ error: `Invalid person_type. Must be one of: ${VALID_TYPES.join(', ')}` }, { status: 400 });
    if (typeof person_id !== 'number' && !Number.isInteger(Number(person_id)))
      return NextResponse.json({ error: 'Invalid person_id' }, { status: 400 });

    const adminName = session.user?.name || 'Admin';

    // ── DEBUG: alamin natin ano talaga laman ng session.user ──
    console.log('DEBUG /api/ids POST — session.user:', JSON.stringify(session.user, null, 2));

    const rawAdminId = (session.user as any)?.id;
    const adminId = Number(rawAdminId);
    const safeAdminId = Number.isFinite(adminId) ? adminId : 0;

    console.log('DEBUG rawAdminId:', rawAdminId, '| typeof:', typeof rawAdminId, '| converted:', safeAdminId);

    const personIdNum = Number(person_id);

    await query<any>(
      'INSERT INTO generated_ids (person_id, person_type, generated_by) VALUES (?,?,?)',
      [personIdNum, person_type, safeAdminId]
    );

    const { table, numField } = TABLE_MAP[person_type as PersonType];
    const rows = await query<any[]>(
      `SELECT first_name, last_name, ${numField} as id_number FROM ${table} WHERE id=?`,
      [personIdNum]
    );
    if (rows.length) {
      const p = rows[0];
      const personName = `${p.first_name || ''} ${p.last_name || ''}`.trim() || 'Student/Staff';
      await query(
        `INSERT INTO notifications (person_id, person_type, title, message, is_read) VALUES (?,?,?,?,0)`,
        [personIdNum, person_type,
          'YOUR SCHOOL ID IS READY! 🎉',
          `Hello ${personName}! Your ID card (${p.id_number}) has been generated by ${adminName}. Just ask your Adviser to claim your physical ID card.`]
      );
    }
    await logAction({
      adminId: safeAdminId, adminName,
      actionType: 'GENERATE_ID', module: 'CREATE_ID',
      targetId: personIdNum,
      details: `Generated ${person_type} ID · person_id: ${personIdNum}`,
    });
    return NextResponse.json({ success: true });
  } catch (e: any) {
    console.error('DEBUG /api/ids POST error:', e);
    return NextResponse.json({ error: e.message || 'Server error' }, { status: 500 });
  }
}